// GENERATED by scripts/generate-big-cities.mjs — do not edit by hand, re-run the generator.
// "Big city" = GeoNames population >= 70,000 in IT/ES/FI, city districts excluded.
export const BIG_CITIES = [
  { name: "Madrid", country: 'ES', coords: [40.4165, -3.7026] }, // 3256k
  { name: "Barcelona", country: 'ES', coords: [41.3888, 2.159] }, // 1686k
  { name: "Valencia", country: 'ES', coords: [39.4739, -0.3797] }, // 824k
  { name: "Zaragoza", country: 'ES', coords: [41.6561, -0.8773] }, // 687k
  { name: "Sevilla", country: 'ES', coords: [37.3828, -5.9732] }, // 687k
  { name: "Málaga", country: 'ES', coords: [36.7202, -4.4203] }, // 592k
  { name: "Murcia", country: 'ES', coords: [37.987, -1.13] }, // 472k
  { name: "Palma", country: 'ES', coords: [39.5694, 2.6502] }, // 438k
  { name: "Las Palmas de Gran Canaria", country: 'ES', coords: [28.1018, -15.4157] }, // 384k
  { name: "Alicante", country: 'ES', coords: [38.3452, -0.4815] }, // 349k
  { name: "Bilbao", country: 'ES', coords: [43.2627, -2.9253] }, // 347k
  { name: "Córdoba", country: 'ES', coords: [37.8916, -4.7728] }, // 326k
  { name: "Valladolid", country: 'ES', coords: [41.6554, -4.7235] }, // 301k
  { name: "Vigo", country: 'ES', coords: [42.2328, -8.7226] }, // 294k
  { name: "Gijón", country: 'ES', coords: [43.5357, -5.6615] }, // 272k
  { name: "Gasteiz / Vitoria", country: 'ES', coords: [42.85, -2.6727] }, // 257k
  { name: "L'Hospitalet de Llobregat", country: 'ES', coords: [41.3597, 2.1003] }, // 257k
  { name: "A Coruña", country: 'ES', coords: [43.3713, -8.396] }, // 250k
  { name: "Elche", country: 'ES', coords: [38.2622, -0.7011] }, // 235k
  { name: "Granada", country: 'ES', coords: [37.1882, -3.6067] }, // 234k
  { name: "Oviedo", country: 'ES', coords: [43.3603, -5.8448] }, // 220k
  { name: "Terrassa", country: 'ES', coords: [41.5667, 2.0167] }, // 219k
  { name: "Badalona", country: 'ES', coords: [41.45, 2.2474] }, // 218k
  { name: "Cartagena", country: 'ES', coords: [37.602, -0.984] }, // 214k
  { name: "Jerez de la Frontera", country: 'ES', coords: [36.6865, -6.1361] }, // 213k
  { name: "Sabadell", country: 'ES', coords: [41.5433, 2.1094] }, // 212k
  { name: "Santa Cruz de Tenerife", country: 'ES', coords: [28.4682, -16.2546] }, // 211k
  { name: "Pamplona", country: 'ES', coords: [42.8169, -1.6432] }, // 208k
  { name: "Móstoles", country: 'ES', coords: [40.3223, -3.865] }, // 207k
  { name: "Almería", country: 'ES', coords: [36.8381, -2.4597] }, // 197k
  { name: "Alcalá de Henares", country: 'ES', coords: [40.4821, -3.36] }, // 194k
  { name: "Fuenlabrada", country: 'ES', coords: [40.2842, -3.7942] }, // 190k
  { name: "Leganés", country: 'ES', coords: [40.3272, -3.7635] }, // 188k
  { name: "Getafe", country: 'ES', coords: [40.3057, -3.733] }, // 188k
  { name: "Donostia / San Sebastián", country: 'ES', coords: [43.3128, -1.975] }, // 185k
  { name: "Burgos", country: 'ES', coords: [42.3411, -3.7018] }, // 176k
  { name: "Santander", country: 'ES', coords: [43.4659, -3.8049] }, // 174k
  { name: "Albacete", country: 'ES', coords: [38.9942, -1.8564] }, // 173k
  { name: "Alcorcón", country: 'ES', coords: [40.3458, -3.8249] }, // 172k
  { name: "Castelló de la Plana", country: 'ES', coords: [39.9857, -0.0493] }, // 172k
  { name: "Marbella", country: 'ES', coords: [36.5154, -4.8858] }, // 156k
  { name: "Logroño", country: 'ES', coords: [42.4661, -2.4512] }, // 151k
  { name: "La Laguna", country: 'ES', coords: [28.4853, -16.3201] }, // 151k
  { name: "Badajoz", country: 'ES', coords: [38.8779, -6.9706] }, // 151k
  { name: "Salamanca", country: 'ES', coords: [40.9688, -5.6639] }, // 145k
  { name: "Huelva", country: 'ES', coords: [37.2664, -6.94] }, // 144k
  { name: "Tarragona", country: 'ES', coords: [41.1191, 1.2454] }, // 142k
  { name: "Lleida", country: 'ES', coords: [41.6167, 0.6222] }, // 141k
  { name: "Mataró", country: 'ES', coords: [41.5421, 2.4445] }, // 127k
  { name: "León", country: 'ES', coords: [42.6, -5.5703] }, // 125k
  { name: "Telde", country: 'ES', coords: [27.9924, -15.4192] }, // 123k
  { name: "Dos Hermanas", country: 'ES', coords: [37.2829, -5.9209] }, // 123k
  { name: "Algeciras", country: 'ES', coords: [36.1333, -5.4505] }, // 121k
  { name: "Santa Coloma de Gramenet", country: 'ES', coords: [41.4515, 2.2081] }, // 119k
  { name: "Torrejón de Ardoz", country: 'ES', coords: [40.4554, -3.4697] }, // 118k
  { name: "Cadiz", country: 'ES', coords: [36.5267, -6.2891] }, // 117k
  { name: "Alcobendas", country: 'ES', coords: [40.5475, -3.642] }, // 116k
  { name: "Parla", country: 'ES', coords: [40.236, -3.7675] }, // 116k
  { name: "Jaén", country: 'ES', coords: [37.7692, -3.7903] }, // 113k
  { name: "Ourense", country: 'ES', coords: [42.3367, -7.8641] }, // 105k
  { name: "Reus", country: 'ES', coords: [41.1561, 1.1069] }, // 103k
  { name: "Orihuela", country: 'ES', coords: [38.0848, -0.944] }, // 101k
  { name: "Barakaldo", country: 'ES', coords: [43.2964, -2.9881] }, // 100k
  { name: "Girona", country: 'ES', coords: [41.9831, 2.8249] }, // 100k
  { name: "Santiago de Compostela", country: 'ES', coords: [42.8805, -8.5457] }, // 100k
  { name: "Lugo", country: 'ES', coords: [43.0099, -7.556] }, // 98k
  { name: "Cáceres", country: 'ES', coords: [39.4765, -6.3722] }, // 96k
  { name: "Las Rozas de Madrid", country: 'ES', coords: [40.4929, -3.8737] }, // 96k
  { name: "San Fernando", country: 'ES', coords: [36.4759, -6.1982] }, // 95k
  { name: "Roquetas de Mar", country: 'ES', coords: [36.7642, -2.6147] }, // 95k
  { name: "Guadalajara", country: 'ES', coords: [40.6286, -3.1618] }, // 93k
  { name: "Lorca", country: 'ES', coords: [37.6712, -1.7017] }, // 93k
  { name: "Talavera de la Reina", country: 'ES', coords: [39.9635, -4.8308] }, // 89k
  { name: "El Puerto de Santa María", country: 'ES', coords: [36.5939, -6.233] }, // 88k
  { name: "Cornellà de Llobregat", country: 'ES', coords: [41.35, 2.0833] }, // 87k
  { name: "Toledo", country: 'ES', coords: [39.8581, -4.0226] }, // 87k
  { name: "Melilla", country: 'ES', coords: [35.2937, -2.9383] }, // 86k
  { name: "El Ejido", country: 'ES', coords: [36.7763, -2.8146] }, // 85k
  { name: "Chiclana de la Frontera", country: 'ES', coords: [36.4198, -6.1437] }, // 84k
  { name: "Ceuta", country: 'ES', coords: [35.8892, -5.3204] }, // 83k
  { name: "Pontevedra", country: 'ES', coords: [42.431, -8.6443] }, // 83k
  { name: "Torrevieja", country: 'ES', coords: [37.9787, -0.6822] }, // 83k
  { name: "Sant Boi de Llobregat", country: 'ES', coords: [41.3436, 2.0366] }, // 82k
  { name: "Pozuelo de Alarcón", country: 'ES', coords: [40.4329, -3.8134] }, // 82k
  { name: "Coslada", country: 'ES', coords: [40.4238, -3.5613] }, // 82k
  { name: "Getxo", country: 'ES', coords: [43.3569, -3.0115] }, // 81k
  { name: "Mijas", country: 'ES', coords: [36.5958, -4.6373] }, // 81k
  { name: "Sant Cugat del Vallès", country: 'ES', coords: [41.4706, 2.0861] }, // 79k
  { name: "Avilés", country: 'ES', coords: [43.5547, -5.9248] }, // 79k
  { name: "Palencia", country: 'ES', coords: [42.0095, -4.5241] }, // 79k
  { name: "Arona", country: 'ES', coords: [28.0996, -16.681] }, // 79k
  { name: "Torrent", country: 'ES', coords: [39.437, -0.4655] }, // 79k
  { name: "Manresa", country: 'ES', coords: [41.7281, 1.824] }, // 76k
  { name: "San Sebastián de los Reyes", country: 'ES', coords: [40.5555, -3.6273] }, // 76k
  { name: "Valdemoro", country: 'ES', coords: [40.1908, -3.6789] }, // 75k
  { name: "Ciudad Real", country: 'ES', coords: [38.9863, -3.9291] }, // 75k
  { name: "Vélez-Málaga", country: 'ES', coords: [36.7811, -4.1027] }, // 74k
  { name: "Gandia", country: 'ES', coords: [38.9667, -0.1833] }, // 74k
  { name: "Rubí", country: 'ES', coords: [41.4923, 2.033] }, // 73k
  { name: "Santa Lucía", country: 'ES', coords: [27.9117, -15.5407] }, // 72k
  { name: "Fuengirola", country: 'ES', coords: [36.54, -4.6247] }, // 71k
  { name: "Benidorm", country: 'ES', coords: [38.5382, -0.131] }, // 70k
  { name: "Alcalá de Guadaira", country: 'ES', coords: [37.3379, -5.8395] }, // 70k
  { name: "Helsinki", country: 'FI', coords: [60.1695, 24.9354] }, // 659k
  { name: "Espoo", country: 'FI', coords: [60.2052, 24.6522] }, // 324k
  { name: "Tampere", country: 'FI', coords: [61.4991, 23.7871] }, // 261k
  { name: "Vantaa", country: 'FI', coords: [60.2941, 25.041] }, // 253k
  { name: "Oulu", country: 'FI', coords: [65.0124, 25.4682] }, // 216k
  { name: "Turku", country: 'FI', coords: [60.4515, 22.2687] }, // 207k
  { name: "Jyväskylä", country: 'FI', coords: [62.2415, 25.7209] }, // 149k
  { name: "Kuopio", country: 'FI', coords: [62.8924, 27.677] }, // 125k
  { name: "Lahti", country: 'FI', coords: [60.9827, 25.6615] }, // 122k
  { name: "Pori", country: 'FI', coords: [61.4807, 21.7852] }, // 83k
  { name: "Joensuu", country: 'FI', coords: [62.6012, 29.7632] }, // 78k
  { name: "Kouvola", country: 'FI', coords: [60.8667, 26.7] }, // 78k
  { name: "Lappeenranta", country: 'FI', coords: [61.0587, 28.1887] }, // 73k
  { name: "Rome", country: 'IT', coords: [41.8919, 12.5113] }, // 2319k
  { name: "Milan", country: 'IT', coords: [45.4643, 9.1895] }, // 1371k
  { name: "Naples", country: 'IT', coords: [40.8522, 14.2681] }, // 909k
  { name: "Turin", country: 'IT', coords: [45.0705, 7.6868] }, // 847k
  { name: "Palermo", country: 'IT', coords: [38.1166, 13.3636] }, // 648k
  { name: "Genoa", country: 'IT', coords: [44.4048, 8.9444] }, // 580k
  { name: "Bologna", country: 'IT', coords: [44.4938, 11.3387] }, // 395k
  { name: "Florence", country: 'IT', coords: [43.7792, 11.2463] }, // 367k
  { name: "Bari", country: 'IT', coords: [41.1207, 16.8698] }, // 316k
  { name: "Catania", country: 'IT', coords: [37.4922, 15.0704] }, // 312k
  { name: "Verona", country: 'IT', coords: [45.4385, 10.9938] }, // 258k
  { name: "Messina", country: 'IT', coords: [38.1939, 15.5526] }, // 220k
  { name: "Trieste", country: 'IT', coords: [45.6495, 13.7768] }, // 204k
  { name: "Padua", country: 'IT', coords: [45.408, 11.8859] }, // 204k
  { name: "Brescia", country: 'IT', coords: [45.5356, 10.2147] }, // 200k
  { name: "Taranto", country: 'IT', coords: [40.4644, 17.2471] }, // 199k
  { name: "Parma", country: 'IT', coords: [44.7993, 10.3262] }, // 198k
  { name: "Prato", country: 'IT', coords: [43.8805, 11.097] }, // 195k
  { name: "Modena", country: 'IT', coords: [44.6478, 10.9254] }, // 185k
  { name: "Reggio Calabria", country: 'IT', coords: [38.1105, 15.6613] }, // 182k
  { name: "Reggio nell'Emilia", country: 'IT', coords: [44.6983, 10.6312] }, // 172k
  { name: "Livorno", country: 'IT', coords: [43.5443, 10.3262] }, // 157k
  { name: "Cagliari", country: 'IT', coords: [39.2305, 9.1192] }, // 149k
  { name: "Rimini", country: 'IT', coords: [44.0575, 12.5653] }, // 149k
  { name: "Foggia", country: 'IT', coords: [41.4584, 15.5519] }, // 137k
  { name: "Ferrara", country: 'IT', coords: [44.838, 11.6206] }, // 132k
  { name: "Salerno", country: 'IT', coords: [40.6754, 14.7933] }, // 126k
  { name: "Monza", country: 'IT', coords: [45.58, 9.2725] }, // 124k
  { name: "Siracusa", country: 'IT', coords: [37.0754, 15.2866] }, // 122k
  { name: "Bergamo", country: 'IT', coords: [45.696, 9.6672] }, // 121k
  { name: "Trento", country: 'IT', coords: [46.0679, 11.1211] }, // 121k
  { name: "Perugia", country: 'IT', coords: [43.1122, 12.3888] }, // 120k
  { name: "Pescara", country: 'IT', coords: [42.4584, 14.2028] }, // 120k
  { name: "Forlì", country: 'IT', coords: [44.2218, 12.0414] }, // 117k
  { name: "Vicenza", country: 'IT', coords: [45.5467, 11.5475] }, // 112k
  { name: "Terni", country: 'IT', coords: [42.5633, 12.6433] }, // 111k
  { name: "Pisa", country: 'IT', coords: [43.7085, 10.4036] }, // 110k
  { name: "Bolzano", country: 'IT', coords: [46.4907, 11.3398] }, // 107k
  { name: "Piacenza", country: 'IT', coords: [45.0524, 9.6934] }, // 104k
  { name: "Novara", country: 'IT', coords: [45.4469, 8.6212] }, // 102k
  { name: "Arezzo", country: 'IT', coords: [43.4628, 11.8807] }, // 101k
  { name: "Udine", country: 'IT', coords: [46.0693, 13.2371] }, // 100k
  { name: "Andria", country: 'IT', coords: [41.2312, 16.298] }, // 100k
  { name: "Cesena", country: 'IT', coords: [44.1391, 12.2431] }, // 97k
  { name: "La Spezia", country: 'IT', coords: [44.103, 9.8238] }, // 93k
  { name: "Barletta", country: 'IT', coords: [41.3143, 16.2816] }, // 93k
  { name: "Alessandria", country: 'IT', coords: [44.9092, 8.6101] }, // 92k
  { name: "Sassari", country: 'IT', coords: [40.7259, 8.5555] }, // 92k
  { name: "Ancona", country: 'IT', coords: [43.6072, 13.5103] }, // 90k
  { name: "Guidonia Montecelio", country: 'IT', coords: [41.9936, 12.7224] }, // 89k
  { name: "Brindisi", country: 'IT', coords: [40.6322, 17.9361] }, // 87k
  { name: "Treviso", country: 'IT', coords: [45.6667, 12.2416] }, // 86k
  { name: "Torre del Greco", country: 'IT', coords: [40.7893, 14.3681] }, // 85k
  { name: "Como", country: 'IT', coords: [45.8082, 9.0832] }, // 85k
  { name: "Busto Arsizio", country: 'IT', coords: [45.6113, 8.8491] }, // 83k
  { name: "Sesto San Giovanni", country: 'IT', coords: [45.5333, 9.2258] }, // 82k
  { name: "Lucca", country: 'IT', coords: [43.8437, 10.5045] }, // 82k
  { name: "Pozzuoli", country: 'IT', coords: [40.8439, 14.0952] }, // 81k
  { name: "Ravenna", country: 'IT', coords: [44.4134, 12.2012] }, // 81k
  { name: "Lecce", country: 'IT', coords: [40.3548, 18.1724] }, // 81k
  { name: "Varese", country: 'IT', coords: [45.8206, 8.8251] }, // 81k
  { name: "Giugliano in Campania", country: 'IT', coords: [40.9285, 14.202] }, // 80k
  { name: "Catanzaro", country: 'IT', coords: [38.8825, 16.6009] }, // 79k
  { name: "Marsala", country: 'IT', coords: [37.7992, 12.4367] }, // 78k
  { name: "Pesaro", country: 'IT', coords: [43.9092, 12.9164] }, // 77k
  { name: "Latina", country: 'IT', coords: [41.4661, 12.9043] }, // 76k
  { name: "Cinisello Balsamo", country: 'IT', coords: [45.5582, 9.2149] }, // 76k
  { name: "Gela", country: 'IT', coords: [37.0738, 14.2404] }, // 75k
  { name: "Aprilia", country: 'IT', coords: [41.5945, 12.6542] }, // 75k
  { name: "Asti", country: 'IT', coords: [44.9016, 8.2075] }, // 74k
  { name: "Ragusa", country: 'IT', coords: [36.9257, 14.7244] }, // 74k
  { name: "Casoria", country: 'IT', coords: [40.9075, 14.293] }, // 74k
  { name: "Pistoia", country: 'IT', coords: [43.9306, 10.9237] }, // 74k
  { name: "Caserta", country: 'IT', coords: [41.0726, 14.3323] }, // 73k
  { name: "Cremona", country: 'IT', coords: [45.1332, 10.0213] }, // 71k
  { name: "Carpi", country: 'IT', coords: [44.7824, 10.8777] }, // 71k
  { name: "Altamura", country: 'IT', coords: [40.8266, 16.5495] }, // 71k
  { name: "Lamezia Terme", country: 'IT', coords: [38.9626, 16.3094] }, // 71k
];
